---
version: '3.7'
services:
  db:
    container_name: mysql
    image: mysql
    #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - learn-ai

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "3308:80"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - learn-ai

  learn-ai:
    container_name: learn-ai
    build: .
    ports:
      - '7050:7050'
    depends_on:
      - db
    restart: always
    networks:
      - learn-ai

networks:
  learn-ai:
    driver: bridge