package ua.dmjdev.dto;

public enum LessonTheme {
    USAGE_OF_ARTICLES("Використання артиклів"),
    TYPES_OF_ARTICLES("Види артиклів"),
    USAGE_OF_SUBSTITUTES("Використання замісників"),
    AVOIDANCE_OF_REPETITIONS("Уникання повторів в мовленні"),
    ENHANCEMENT_OF_CONNECTION_IN_TEXT("Підсилення зв'язку в тексті"),
    VERB_TO_BE_IN_ENGLISH("Дієслово 'бути' в англійській"),
    DESCRIPTION_OF_PERSONS_AND_OBJECTS("Опис особи та предметів"),
    CONFIRMATION_OF_FACTS("Підтвердження фактів"),
    CORRECT_WORD_ORDER("Правильний порядок слів"),
    FORMATION_OF_MEANINGFUL_SENTENCES("Формування змістовних речень"),
    AVOIDANCE_OF_MISUNDERSTANDINGS_IN_SPEECH("Уникання недорозумінь у мовленні"),
    DESCRIPTION_OF_REGULAR_ACTIONS("Опис регулярних дій"),
    DAILY_ROUTINE_AND_HABITS("Повсякденні рутина та звички"),
    GENERAL_FACTS_AND_TRUTH("Загальні факти та правдивість"),
    USAGE_OF_PREPOSITIONS("Використання прийменників"),
    SPATIAL_AND_TEMPORAL_ORIENTATION("Орієнтація в просторі та часі"),
    CONNECTION_BETWEEN_OBJECTS("Зв'язок між предметами"),
    ACTIONS_HAPPENING_NOW("Дії, що відбуваються зараз"),
    FUTURE_PLANS_AND_ARRANGEMENTS("Майбутні плани та домовленості"),
    UNSTABLE_SITUATIONS("Нестабільні ситуації"),
    DESCRIPTION_OF_OBJECTS_AVAILABILITY("Опис наявності предметів"),
    DESCRIPTION_OF_LOCATION("Опис місця розташування"),
    ESTABLISHMENT_OF_FACTS("З'ясування фактів"),
    DESCRIPTION_OF_PAST_EVENTS("Опис минулих подій"),
    USAGE_OF_REGULAR_AND_IRREGULAR_VERBS("Використання звичайних та неправильних дієслів"),
    COMPLETED_ACTIONS_IN_THE_PAST("Завершені дії в минулому"),
    IRREGULAR_VERBS("Неправильні дієслова"),
    DESCRIPTION_OF_PERSONAL_ACTIONS("Опис особистих дій"),
    USAGE_IN_SPOKEN_LANGUAGE("Використання в розмовному мовленні"),
    ACTIONS_IN_PROGRESS_IN_THE_PAST("Дії в процесі у минулому"),
    COMPARISON_OF_EVENTS_IN_THE_PAST("Порівняння подій у минулому"),
    DESCRIPTION_OF_ACTION_DURATION("Опис тривалості дій"),
    USAGE_OF_SOME_ANY_NO("Використання some, any, no"),
    INDICATION_OF_QUANTITY_AND_AVAILABILITY("Позначення кількості та наявності"),
    AVOIDANCE_OF_AMBIGUITIES("Уникання неоднозначностей"),
    DEGREE_OF_COMPARISON("Ступені порівняння"),
    COMPARISON_OF_OBJECTS_BY_CHARACTERISTICS("Порівняння предметів за характеристиками"),
    ENHANCEMENT_OF_COMPARISONS("Підсилення порівнянь"),
    USAGE_OF_ADVERBS("Використання прислівників"),
    DESCRIPTION_OF_ACTIONS_AND_CIRCUMSTANCES("Опис дій та обставин"),
    ENHANCEMENT_OF_EXPRESSION("Підсилення висловлення"),
    FUTURE_EVENTS("Майбутні події"),
    PLANS_AND_ARRANGEMENTS_IN_THE_FUTURE("Плани та домовленості у майбутньому"),
    PREDICTIONS_AND_POSSIBLE_OUTCOMES("Прогнози та можливі результати"),
    FUTURE_PLANS("Майбутні плани"),
    REPLACEMENT_OF_SIMPLE_FUTURE_WITH_TO_BE_GOING_TO("Заміна будущого простого на to be going to"),
    INTENTIONS_AND_PLANS("Наміри та плани"),
    ACTIONS_THAT_HAVE_OCCURRED_BEFORE_THE_SPEAKING_MOMENT("Дії, що відбулися до моменту говоріння"),
    USAGE_OF_PRESENT_PERFECT_WITH_ALREADY_YET_JUST("Використання present perfect з already, yet, just"),
    EXPERIENCE_AND_RESULTS("Досвід та результати"),
    IMPERSONAL_INFINITIVE("Безособовий інфінітив"),
    USAGE_OF_TO_PLUS_VERB("Використання to + дієслово"),
    INFINITIVE_AS_SUBJECT_OR_ADVERB("Інфінітив у функції підмета або обставини"),
    GERUND("Герундій"),
    USAGE_OF_ING_FORM("Використання -ing форми"),
    GERUND_AS_SUBJECT_OBJECT_OR_ADVERB("Герундій у функції підмета, об'єкта або обставини"),
    VERB_MUST("Дієслово must"),
    ENHANCEMENT_OF_OBLIGATION("Підсилення невід'ємності"),
    NECESSITY_AND_OBLIGATION("Доцільність та необхідність"),
    VERB_HAVE_TO("Дієслово have to"),
    OBLIGATIONS_AND_NECESSITY("Зобов'язання та необхідність"),
    DIFFERENCES_BETWEEN_MUST_AND_HAVE_TO("Відмінності між must та have to"),
    VERB_SHOULD("Дієслово should"),
    RECOMMENDATIONS_AND_ADVICE("Рекомендації та поради"),
    SOFT_OBLIGATION("М'яке зобов'язання"),
    CONDITIONAL_SENTENCES("Умовні речення"),
    USAGE_OF_IF_CONSTRUCTIONS("Використання if-конструкцій"),
    EXPRESSION_OF_CONDITIONS_AND_THEIR_RESULTS("Вираження умов та їх результатів"),
    USAGE_OF_USED_TO("Використання used to"),
    DESCRIPTION_OF_PAST_HABITS_AND_SITUATIONS("Опис минулих звичок та ситуацій"),
    COMPARISON_OF_USED_TO_AND_WOULD("Порівняння used to та would"),
    TAG_QUESTIONS("Тегові питання"),
    ADDITION_OF_TAGS_TO_SENTENCES("Додавання тегів до речень"),
    AFFIRMATION_OR_NEGATION("Підтвердження або заперечення"),
    PAST_PERFECT("Past Perfect"),
    EVENTS_THAT_HAPPENED_BEFORE_A_SPECIFIC_POINT_IN_THE_PAST("Події, які відбулися до певного моменту в минулому"),
    COMPARISON_OF_PAST_PERFECT_AND_PAST_SIMPLE("Порівняння Past Perfect та Past Simple"),
    SEQUENCE_OF_TENSES("Узгодження часів"),
    CONNECTION_OF_TENSES_IN_COMPLEX_SENTENCES("Зв'язок часів у складних реченнях"),
    CORRECT_USAGE_OF_TENSES("Правильне використання часів"),
    PRESENT_PERFECT_CONTINUOUS("Present Perfect Continuous"),
    ACTIONS_IN_PROGRESS_UP_TO_THE_PRESENT_MOMENT("Дії, що тривають до моменту говоріння"),
    COMPARISON_OF_PRESENT_PERFECT_CONTINUOUS_AND_PRESENT_PERFECT("Порівняння Present Perfect Continuous та Present Perfect"),
    PASSIVE_VOICE("Passive Voice"),
    ACTIVE_AND_PASSIVE_VERBAL_STATEMENTS("Активне та пасивне дієприкметникове становище"),
    CONSTRUCTION_OF_PASSIVE_CONSTRUCTIONS("Побудова пасивних конструкцій"),
    MODAL_VERBS_CAN_AND_COULD("Модальні дієслова can та could"),
    POSSIBILITIES_AND_PERMISSIONS("Можливості та дозволи"),
    POSSIBLE_PAST("Можливе минуле"),
    MODAL_VERBS_MAY_AND_MIGHT("Модальні дієслова may та might"),
    POSSIBILITIES_AND_INDEFINITENESS("Можливості та невизначеність"),
    PERMISSION_AND_POSSIBILITY("Дозвіл та можливість"),
    PUNCTUATION("Пунктуація"),
    USAGE_OF_PUNCTUATION_MARKS("Використання розділових знаків"),
    RULES_OF_TEXT_FORMATTING("Правила оформлення текстів"),
    FUTURE_PERFECT_CONTINUOUS("Future Perfect Continuous"),
    EVENTS_THAT_WILL_CONTINUE_UP_TO_A_SPECIFIC_POINT_IN_THE_FUTURE("Події, які триватимуть до певного моменту у майбутньому"),
    COMPARISON_OF_FUTURE_PERFECT_CONTINUOUS_AND_FUTURE_PERFECT("Порівняння Future Perfect Continuous та Future Perfect"),
    FUTURE_IN_THE_PAST("Future in the Past"),
    EXPRESSION_OF_FUTURE_EVENTS_FROM_A_PAST_PERSPECTIVE("Вираження майбутньої події з погляду минулого"),
    CONDITIONAL_CONSTRUCTIONS_FROM_THE_PAST_FOR_THE_FUTURE("Умовні конструкції минулого для майбутнього");

    private String description;

    LessonTheme(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}

