package ua.dmjdev.dto;

public enum Rule {
    PRONOUNS,
    TO_BE,
    ARTICLES,
    WORD_ORDER,
    PRESENT_SIMPLE,
    PREPOSITIONS,
    PRESENT_CONTINUOUS,
    THERE_IS_THERE_ARE,
    PAST_SIMPLE,
    IRREGULAR_VERBS,
    PAST_CONTINUOUS,
    SOME_ANY_NO,
    DEGREE_OF_COMPARISON,
    ADVERBS,
    FUTURE_SIMPLE,
    TO_BE_GOING_TO,
    PRESENT_PERFECT,
    INFINITIVE,
    GERUND,
    MODAL_VERBS_MUST,
    MODAL_VERBS_HAVE_TO,
    MODAL_VERBS_SHOULD,
    MODAL_VERBS_MAY_MIGHT,
    MODAL_VERBS_CAN_COULD,

    CONDITIONALS,
    USED_TO,
    QUESTION_TAGS,
    PAST_PERFECT,
    AGREEMENT_OF_TENSES,
    PRESENT_PERFECT_CONTINUOUS,
    PASSIVE_VOICE,

    PUNCTUATION,
    FUTURE_PERFECT_CONTINUOUS,
    FUTURE_IN_THE_PAST,


}

